import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, Route, Routes, useNavigate, useParams, useSearchParams} from 'react-router-dom';
import {QueryClient, QueryClientProvider, useQuery} from '@tanstack/react-query';
import './styles.css';

const api=async<T,>(path:string):Promise<T>=>{const r=await fetch(`/api/v1${path}`); if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e?.error?.message||e?.detail||'Request failed');} return r.json()};
const fmt=(n:any, pct=false)=>n===null||n===undefined?'—':pct?`${(Number(n)*100).toFixed(1)}%`:new Intl.NumberFormat().format(Number(Number(n).toFixed(Number(n)%1?1:0)));
function State({query,children}:{query:any,children:(d:any)=>React.ReactNode}){if(query.isLoading)return <p role="status">Loading data…</p>;if(query.isError)return <div className="state"><p role="alert">{query.error.message}</p><button onClick={()=>query.refetch()}>Retry</button></div>;return <>{children(query.data)}</>}
function Layout(){return <><header><Link to="/">NBA Local Explorer</Link><nav><Link to="/players">Players</Link><Link to="/shots">Shot Explorer</Link></nav></header><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/players" element={<Players/>}/><Route path="/players/:playerId" element={<Player/>}/><Route path="/shots" element={<Shots/>}/></Routes></main></>}
function Season({value,onChange,catalog}:{value:string,onChange:(x:string)=>void,catalog:any}){return <label>Season <select value={value} onChange={e=>onChange(e.target.value)}>{catalog?.seasons?.map((s:string)=><option key={s}>{s}</option>)}</select></label>}
function Dashboard(){const q=useQuery({queryKey:['catalog'],queryFn:()=>api<any>('/catalog')});const [season,setSeason]=useState('');return <State query={q}>{d=>{const chosen=season||d.seasons[0];return <><h1>Local NBA data</h1><Season catalog={d} value={chosen} onChange={setSeason}/><section className="cards">{Object.entries(d.datasets).map(([name,v]:any)=><article key={name}><h2>{name.replaceAll('_',' ')}</h2><strong>{fmt(v.rows)}</strong> rows<br/><small>{v.available?'Available':'Unavailable'}</small></article>)}</section><p>Shot charts cover regular-season field-goal attempts for extraction-eligible players. Court bins are fixed 25-unit cells from x −250…250 and y −50…420.</p><p><Link className="button" to={`/players?season=${chosen}`}>Explore players</Link> <Link className="button" to={`/shots?season=${chosen}`}>Explore shots</Link></p></>}}</State>}
function Players(){const [p,setP]=useSearchParams();const season=p.get('season')||'';const [search,setSearch]=useState(p.get('q')||'');const page=Number(p.get('page')||1);const qs=new URLSearchParams({season,page:String(page),page_size:'50',q:search});const q=useQuery({queryKey:['players',qs.toString()],queryFn:()=>api<any>(`/players?${qs}`),enabled:!!season});const cat=useQuery({queryKey:['catalog'],queryFn:()=>api<any>('/catalog')});const go=(x:any)=>{const n=new URLSearchParams(p);Object.entries(x).forEach(([k,v])=>n.set(k,String(v)));setP(n)};return <><h1>Player statistics</h1><div className="filters"><State query={cat}>{d=><Season catalog={d} value={season||d.seasons[0]} onChange={x=>go({season:x,page:1})}/>}</State><label>Search player <input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go({q:search,page:1})}/></label><button onClick={()=>go({q:search,page:1})}>Apply</button></div><State query={q}>{d=><><p>{fmt(d.meta.total)} matching team-season rows</p><Table rows={d.items} player/><Pager meta={d.meta} go={x=>go({page:x})}/></>}</State></>}
const cols=['PLAYER_NAME','TEAM_ABBREVIATION','GP','MIN','PTS','FGA','FG_PCT','FG3A','FG3_PCT','REB','AST','TOV','STL','BLK','PLUS_MINUS'];
function cellValue(column:string,value:any){if(column==='SHOT_MADE_FLAG')return value?'Made ✓':'Miss ✕';if(value===null||value===undefined)return '—';return typeof value==='number'?fmt(value,column.includes('PCT')):String(value)}
function Table({rows,player=false}:{rows:any[],player?:boolean}){const nav=useNavigate();if(!rows.length)return <p>No matching results.</p>;return <div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).filter(k=>cols.includes(k)||['GAME_DATE','EVENT_TYPE','SHOT_MADE_FLAG','SHOT_TYPE','SHOT_DISTANCE','LOC_X','LOC_Y'].includes(k)).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>player&&nav(`/players/${r.PLAYER_ID}?season=${r.season}`)} className={player?'clickable':''}>{Object.keys(r).filter(k=>cols.includes(k)||['GAME_DATE','EVENT_TYPE','SHOT_MADE_FLAG','SHOT_TYPE','SHOT_DISTANCE','LOC_X','LOC_Y'].includes(k)).map(k=><td key={k}>{cellValue(k,r[k])}</td>)}</tr>)}</tbody></table></div>}
function Pager({meta,go}:{meta:any,go:(x:number)=>void}){return <div className="pager"><button disabled={meta.page===1} onClick={()=>go(meta.page-1)}>Previous</button><span>Page {meta.page} of {Math.max(1,Math.ceil(meta.total/meta.page_size))}</span><button disabled={meta.page*meta.page_size>=meta.total} onClick={()=>go(meta.page+1)}>Next</button></div>}
function Player(){const {playerId=''}=useParams();const [p,setP]=useSearchParams();const season=p.get('season')||'';const d=useQuery({queryKey:['player',playerId,season],queryFn:()=>api<any>(`/players/${playerId}${season?`?season=${season}`:''}`)});return <State query={d}>{data=>{const selected=data.season_rows[0];return <><h1>{data.player.FULL_NAME||selected.PLAYER_NAME}</h1><p>Source team rows are shown; no total aggregate is calculated.</p>{selected&&<section className="cards">{['PTS','REB','AST','MIN','GP','FG_PCT'].map(k=><article key={k}><small>{k}{['PTS','REB','AST'].includes(k)?' /100 possessions':''}</small><strong>{fmt(selected[k],k.includes('PCT'))}</strong></article>)}</section>}<h2>Available seasons and teams</h2><Table rows={data.season_rows}/>{selected&&<p><Link className="button" to={`/shots?season=${selected.season}&player_id=${playerId}`}>Open shot explorer</Link></p>}</>}}</State>}
function Court({map}:{map:any}){const g=map.grid;const x=(n:number)=>(n-g.x_min)/(g.x_max-g.x_min)*500;const y=(n:number)=>500-(n-g.y_min)/(g.y_max-g.y_min)*470;return <svg className="court" viewBox="0 0 500 500" role="img" aria-label={`${map.mode} shot map with ${map.returned} rendered records`}><rect width="500" height="500" fill="#f7e6c4"/><path d="M0 500H500M190 500V360H310V500M220 360a30 30 0 0 1 60 0M250 452a8 8 0 1 0 0 .1" fill="none" stroke="#532" strokeWidth="3"/>{map.items.map((r:any,i:number)=>map.mode==='points'?<circle key={i} cx={x(r.LOC_X)} cy={y(r.LOC_Y)} r="3" className={r.SHOT_MADE_FLAG?'make':'miss'}/>:<rect key={i} x={x(r.x)} y={y(r.y+25)} width="25" height="25" opacity=".15" fill="#b22"><title>{r.attempts} attempts, {r.makes} makes, {fmt(r.fg_pct,true)}</title></rect>)}</svg>}
function PlayerNameSearch({season,playerId,onSelect,onClear}:{season:string,playerId:string,onSelect:(id:string)=>void,onClear:()=>void}){const [search,setSearch]=useState('');const term=search.trim();const lookup=useQuery({queryKey:['player-lookup',season,term],queryFn:()=>api<any>(`/lookups/players?${new URLSearchParams({q:term, ...(season?{season}:{})})}`),enabled:term.length>0});const selected=useQuery({queryKey:['selected-player',playerId],queryFn:()=>api<any>(`/players/${playerId}`),enabled:!!playerId});return <div className="player-search"><label>Player name <input type="search" value={search} placeholder="Search by player name" onChange={e=>{setSearch(e.target.value);if(playerId)onClear()}} aria-controls="player-name-results"/></label>{playerId&&<div className="selected-player">Selected: {selected.data?.player?.FULL_NAME||'Loading player…'} <button type="button" onClick={onClear}>Clear</button></div>}{term&&<div id="player-name-results" className="player-name-results" role="listbox">{lookup.isLoading&&<span>Searching players…</span>}{lookup.data?.items?.map((item:any)=><button key={item.PLAYER_ID} type="button" role="option" onClick={()=>{onSelect(String(item.PLAYER_ID));setSearch('')}}>{item.FULL_NAME}</button>)}{lookup.isSuccess&&!lookup.data.items.length&&<span>No matching players.</span>}</div>}</div>}
function Shots(){const [p,setP]=useSearchParams();const season=p.get('season')||'';const player=p.get('player_id')||'';const base=new URLSearchParams({season, ...(player?{player_id:player}:{})});const cat=useQuery({queryKey:['catalog'],queryFn:()=>api<any>('/catalog')});const sum=useQuery({queryKey:['sum',base.toString()],queryFn:()=>api<any>(`/shots/summary?${base}`),enabled:!!season});const map=useQuery({queryKey:['map',base.toString()],queryFn:()=>api<any>(`/shots/map?${base}`),enabled:!!season});const shots=useQuery({queryKey:['shots',base.toString()],queryFn:()=>api<any>(`/shots?${base}&page_size=25`),enabled:!!season});const set=(k:string,v:string)=>{const n=new URLSearchParams(p);if(v)n.set(k,v);else n.delete(k);setP(n)};return <><h1>Shot explorer</h1><div className="filters"><State query={cat}>{d=><Season catalog={d} value={season||d.seasons[0]} onChange={x=>set('season',x)}/>}</State><PlayerNameSearch season={season} playerId={player} onSelect={x=>set('player_id',x)} onClear={()=>set('player_id','')}/></div><State query={sum}>{s=><section className="cards">{[['FGA',s.fga],['FGM',s.fgm],['FG%',fmt(s.fg_pct,true)],['2P%',fmt(s.two_pct,true)],['3P%',fmt(s.three_pct,true)],['Avg. distance',s.avg_distance]].map(([k,v])=><article key={String(k)}><small>{k}</small><strong>{fmt(v)}</strong></article>)}</section>}</State><State query={map}>{m=><><p role="status">{m.mode==='bins'?'Aggregated fixed 25-unit grid (points are limited to player-scoped results of 5,000 shots or fewer).':'Individual makes (solid) and misses (outlined).'}</p><Court map={m}/></>}</State><h2>Shot results</h2><State query={shots}>{x=><Table rows={x.items}/>}</State></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><BrowserRouter><Layout/></BrowserRouter></QueryClientProvider></React.StrictMode>);
